apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics-catalogue
  name: metrics-catalogue
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: metrics-catalogue
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-catalogue
  name: metrics-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-catalogue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metrics-catalogue
    spec:
      containers:
        - env:
            - name: TSCALE_HOST
              value: "timescaledb"
            - name: TSCALE_NAME
              value: aces
            - name: TSCALE_DB
              value: aces
            - name: TSCALE_PASS
              value: aces
            - name: NEO4J_HOST
              value: neo4j
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASS
              value: neo4j290292
          image: pkapsalismartel/metrics_catalogue:v0.15
          name: metrics-catalogue
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      hostname: metrics-catalogue
      restartPolicy: Always