apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-db
  name: mlflow-db
spec:
  ports:
  # PostgreSQL wire protocol clients.
  - port: 5432
    targetPort: 5432
    name: mlflow-db
  selector:
    app: mlflow-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-db
  labels:
    app: mlflow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-db
  template:
    metadata:
      labels:
        app: mlflow-db
    spec:
      containers:
      - name: mlflow-db
        image: postgres:15.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: mlflow-db
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "mlflow"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: mlflow-db-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: mlflow-db-pv
        persistentVolumeClaim:
          claimName: mlflow-db-pvc